#include <math.h>
#include <time.h>
#include <stdio.h>
#include <stdint.h>
#include <errno.h>
#include <softPwm.h>
#include <wiringPi.h>
#include <wiringPiI2C.h>
#include <wiringSerial.h>
#include <string.h>
#include <iostream>
#include <fstream>